CREATE TABLE MEMBER(
    MEM_NO NUMBER PRIMARY KEY,
    MEM_ID VARCHAR(20),
    MEM_PWD VARCHAR(20),
    PLAY_NO VARCHAR(20)
);

CREATE TABLE MUSIC(
    MUSIC_NO NUMBER PRIMARY KEY,
    MUSIC_TITLE VARCHAR(20),
    MUSIC_MCISAN VARCHAR(20),
    GENRE VARCHAR(20)
);

CREATE TABLE PLAYLIST (
	PLAY_NO	NUMBER	PRIMARY KEY,
	MEM_NO	NUMBER	NOT NULL
);

CREATE SEQUENCE SEQ_MEM;
CREATE SEQUENCE SEQ_MUSIC;

ALTER TABLE PLAYLIST ADD CONSTRAINT PK_PLAYLIST PRIMARY KEY (
	PLAY_NO
);